services:
  # Dịch vụ web
  - type: web
    name: finance-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: >
      sh -c "
        python -m flask db upgrade &&
        gunicorn app:app
      "
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: FLASK_APP
        value: app.py
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: finance-db
          property: connectionString

  # Cơ sở dữ liệu PostgreSQL
databases:
  - name: finance-db
    databaseName: finance_db
    user: finance_user
    plan: free 